export const state = {
    isHelper: false,
    expeditionEndTimes: {},
    modifiersEnabled: true,
    savedLootMod: 1,
    savedRiskMod: -5,
    dailyNextTaskTime: null,
    coreMarketName: null,
    darkMarketName: null,
    soyuzMarketName: null,
    usolMarketName: null,
    coreNextJobsResetAt: null,
    bmiNextJobsResetAt: null,
    soyuzNextJobsResetAt: null,
    usolNextJobsResetAt: null,
    isRefreshing: false,
    refreshQueue: [],
    isProcessingQueue: false,
    pinnedTimers: { daily: false, home_jobs: false, dark_jobs: false, soyuz_jobs: false, usol_jobs: false },
    autoRefresh: { home_jobs: false, dark_jobs: false, soyuz_jobs: false, usol_jobs: false },
    autoRefreshRetry: { home_jobs: null, dark_jobs: null, soyuz_jobs: null, usol_jobs: null },
    lastTimerSeconds: { home_jobs: null, dark_jobs: null, soyuz_jobs: null, usol_jobs: null },
    cachedLoadoutData: null,
    selectedMercenaryId: null,
    mercRestTimers: {},
    autoJobsRunning: false,
    autoFinishAllActive: false,
    autoJobsSelectedTypes: { home: [], dark: [], soyuz: [], usol: [] },
    autoJobsDebugLogs: [],
    autoJobsTracker: [],
    valuableSearchRunning: false,
    valuableSellerRunning: false,
    valuableDebugLogs: [],
    _cachedExpeditionsForVeteranCheck: null,
    autoChosenDecisions: new Set(),
    _specialistTimerInterval: null,
    _renderDebugJobsId: 0,
    _maintTimerInterval: null,
};

export const zoomList = {
    "Lyapun AA8": 2.1, "A/Bver 410": 2.1, "RE-nova v3.0": 2.1,
    "D-Badger v2.2": 2.1, "Porter-triX lr8": 2.1,
    "H0pp3R ced/p 03": 1.8, "Screener Pro r10": 1.8,
    "5CRYPt0L 0J": 2.3, "OmniFlow 12.35X": 2.575,
    "8Pro Series 1870": 2.5, "I-Partner C16-10": 2.6
};
